[2025-06-15T03:29:08.616+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: retail_analytics_airflowDAG.extract scheduled__2025-06-14T00:00:00+00:00 [queued]>
[2025-06-15T03:29:08.628+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: retail_analytics_airflowDAG.extract scheduled__2025-06-14T00:00:00+00:00 [queued]>
[2025-06-15T03:29:08.629+0000] {taskinstance.py:2170} INFO - Starting attempt 3 of 4
[2025-06-15T03:29:08.651+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): extract> on 2025-06-14 00:00:00+00:00
[2025-06-15T03:29:08.657+0000] {standard_task_runner.py:60} INFO - Started process 213 to run task
[2025-06-15T03:29:08.665+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'retail_analytics_***DAG', 'extract', 'scheduled__2025-06-14T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline_dag.py', '--cfg-path', '/tmp/tmpithfazch']
[2025-06-15T03:29:08.671+0000] {standard_task_runner.py:88} INFO - Job 15: Subtask extract
[2025-06-15T03:29:08.707+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-15T03:29:08.751+0000] {task_command.py:423} INFO - Running <TaskInstance: retail_analytics_airflowDAG.extract scheduled__2025-06-14T00:00:00+00:00 [running]> on host cd4f508dcab2
[2025-06-15T03:29:08.836+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='retail_analytics_***DAG' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2025-06-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-14T00:00:00+00:00'
[2025-06-15T03:29:08.837+0000] {data_extract.py:14} INFO - Starting extraction...
[2025-06-15T03:29:08.849+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/compat/_optional.py", line 142, in import_optional_dependency
    module = importlib.import_module(name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'openpyxl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/utils/data_extract.py", line 15, in extract_data
    salesdf, customersdf, inventorydf = generate_data()
  File "/opt/airflow/utils/generate_data.py", line 14, in generate_data
    sales_df = pd.read_excel(os.path.join(project_root, 'data/loaded/loaded_sales_data.xlsx'), sheet_name='Online Retail')
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 478, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 1513, in __init__
    self._reader = self._engines[engine](self._io, storage_options=storage_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_openpyxl.py", line 548, in __init__
    import_optional_dependency("openpyxl")
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/compat/_optional.py", line 145, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
[2025-06-15T03:29:08.868+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=retail_analytics_***DAG, task_id=extract, execution_date=20250614T000000, start_date=20250615T032908, end_date=20250615T032908
[2025-06-15T03:29:08.886+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 15 for task extract (Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.; 213)
[2025-06-15T03:29:08.913+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-15T03:29:08.940+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
